// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCTj9fsNn5sOFD7W5CsHNn_5KkBMXtYfbo',
//     appId: '1:526810364014:web:32c113da719438ed490e7f',
//     messagingSenderId: '526810364014',
//     projectId: 'webrtcvediocall',
//     authDomain: 'webrtcvediocall.firebaseapp.com',
//     storageBucket: 'webrtcvediocall.firebasestorage.app',
//     measurementId: 'G-RL90BN92Q3',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyC8nws9rk_ZE99OzWGlBLutTvGzZk630og',
//     appId: '1:526810364014:android:3a158732a7a25ae9490e7f',
//     messagingSenderId: '526810364014',
//     projectId: 'webrtcvediocall',
//     storageBucket: 'webrtcvediocall.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBmZz4WvLbzMlavkawHpV37bEZEdFTW1WY',
//     appId: '1:526810364014:ios:6d6452cf7c60df85490e7f',
//     messagingSenderId: '526810364014',
//     projectId: 'webrtcvediocall',
//     storageBucket: 'webrtcvediocall.firebasestorage.app',
//     iosBundleId: 'com.example.webrtc',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBmZz4WvLbzMlavkawHpV37bEZEdFTW1WY',
//     appId: '1:526810364014:ios:6d6452cf7c60df85490e7f',
//     messagingSenderId: '526810364014',
//     projectId: 'webrtcvediocall',
//     storageBucket: 'webrtcvediocall.firebasestorage.app',
//     iosBundleId: 'com.example.webrtc',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyCTj9fsNn5sOFD7W5CsHNn_5KkBMXtYfbo',
//     appId: '1:526810364014:web:2e335419cbfadcc3490e7f',
//     messagingSenderId: '526810364014',
//     projectId: 'webrtcvediocall',
//     authDomain: 'webrtcvediocall.firebaseapp.com',
//     storageBucket: 'webrtcvediocall.firebasestorage.app',
//     measurementId: 'G-GEHTQWQLHD',
//   );
// }
